import { Stamp } from "@/components/StampCard";

export const DEMO_STAMPS: Stamp[] = [
  {
    id: "1",
    catalogNumber: "PT-1995-01",
    country: "Portugal",
    year: 1995,
    faceValue: "1€",
    topology: "Rectangular",
    fdc: true,
    setName: "Europa 1995",
    color: "Blue",
    perforation: "14x14",
    watermark: "None",
    theme: "Historical Figures",
    condition: "Mint",
    estimatedPrice: 5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "History"],
    description: "Commemorative stamp featuring King João II",
  },
  {
    id: "2",
    catalogNumber: "FR-2000-12",
    country: "France",
    year: 2000,
    faceValue: "2€",
    topology: "Square",
    fdc: false,
    setName: "Millennium",
    color: "Red",
    perforation: "13x13",
    watermark: "Small fleur-de-lis",
    theme: "Millennium Celebration",
    condition: "Used",
    estimatedPrice: 3,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Millennium"],
    description: "Square stamp issued for the millennium celebration in France",
  },
  {
    id: "3",
    catalogNumber: "DE-1980-05",
    country: "Germany",
    year: 1980,
    faceValue: "0.50€",
    topology: "Rectangular",
    fdc: true,
    setName: "Animals Series",
    color: "Brown",
    perforation: "14x14",
    watermark: "None",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 2.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Animals"],
    description: "Rectangular stamp featuring a German eagle",
  },
  {
    id: "4",
    catalogNumber: "US-1975-03",
    country: "USA",
    year: 1975,
    faceValue: "$0.10",
    topology: "Circular",
    fdc: false,
    setName: "Historic Figures",
    color: "Red",
    perforation: "12x12",
    watermark: "Liberty Bell",
    theme: "Presidents",
    condition: "Used",
    estimatedPrice: 1,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["America", "History"],
    description: "Circular stamp featuring US president",
  },
  {
    id: "5",
    catalogNumber: "UK-2010-01",
    country: "United Kingdom",
    year: 2010,
    faceValue: "£1",
    topology: "Rectangular",
    fdc: true,
    setName: "Royalty",
    color: "Blue",
    perforation: "14x14",
    watermark: "Crown",
    theme: "Queen Elizabeth II",
    condition: "Mint",
    estimatedPrice: 6,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Royalty"],
    description: "Commemorative stamp featuring Queen Elizabeth II",
  },
  // Add more for variety
  {
    id: "6",
    catalogNumber: "JP-1990-04",
    country: "Japan",
    year: 1990,
    faceValue: "100¥",
    topology: "Rectangular",
    fdc: true,
    setName: "Cherry Blossom",
    color: "Pink",
    perforation: "13x13",
    watermark: "Cherry",
    theme: "Nature",
    condition: "Mint",
    estimatedPrice: 4,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Asia", "Nature"],
    description: "Cherry Blossom stamp from Japan",
  },
  {
    id: "7",
    catalogNumber: "IT-1985-09",
    country: "Italy",
    year: 1985,
    faceValue: "500L",
    topology: "Rectangular",
    fdc: false,
    setName: "Art Series",
    color: "Multicolor",
    perforation: "14x14",
    watermark: "None",
    theme: "Renaissance",
    condition: "Used",
    estimatedPrice: 3.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Art"],
    description: "Renaissance painting featured on stamp",
  },
  {
    id: "8",
    catalogNumber: "CA-2005-02",
    country: "Canada",
    year: 2005,
    faceValue: "1.50$",
    topology: "Square",
    fdc: true,
    setName: "Wildlife",
    color: "Green",
    perforation: "13x13",
    watermark: "Maple Leaf",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 4.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["America", "Nature"],
    description: "Canadian wildlife stamp",
  },
  {
    id: "9",
    catalogNumber: "AU-2015-01",
    country: "Australia",
    year: 2015,
    faceValue: "2$",
    topology: "Rectangular",
    fdc: true,
    setName: "Nature Series",
    color: "Blue",
    perforation: "14x14",
    watermark: "Kangaroo",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 5.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Oceania", "Nature"],
    description: "Australian stamp featuring kangaroo",
  },
  {
    id: "10",
    catalogNumber: "BR-2001-07",
    country: "Brazil",
    year: 2001,
    faceValue: "R$1.20",
    topology: "Rectangular",
    fdc: false,
    setName: "Carnival",
    color: "Red",
    perforation: "13x13",
    watermark: "None",
    theme: "Culture",
    condition: "Used",
    estimatedPrice: 2.8,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["South America", "Culture"],
    description: "Brazil Carnival stamp",
  },
// --- EUROPE ---
{
  id: "11",
  catalogNumber: "ES-1982-OLY",
  country: "Spain",
  year: 1982,
  faceValue: "25P",
  topology: "Rectangular",
  fdc: true,
  setName: "Barcelona Olympics",
  color: "Multicolor",
  perforation: "13¾",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Sports"],
  description: "Issued for the 1982 Olympic Games",
},
{
  id: "12",
  catalogNumber: "NL-1998-01",
  country: "Netherlands",
  year: 1998,
  faceValue: "80c",
  topology: "Rectangular",
  fdc: false,
  setName: "Modern Art",
  color: "Yellow",
  perforation: "14",
  watermark: "None",
  theme: "Art",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Art"],
  description: "Modern Dutch art stamp",
},
{
  id: "13",
  catalogNumber: "CH-1970-05",
  country: "Switzerland",
  year: 1970,
  faceValue: "50Rp",
  topology: "Rectangular",
  fdc: true,
  setName: "Alpine Flowers",
  color: "Purple",
  perforation: "11¾",
  watermark: "Cross",
  theme: "Nature",
  condition: "Mint",
  estimatedPrice: 3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Nature"],
  description: "Alpine flower series",
},

// --- CLASSIC THEMES ---
{
  id: "14",
  catalogNumber: "US-1969-AP11",
  country: "USA",
  year: 1969,
  faceValue: "$0.10",
  topology: "Rectangular",
  fdc: true,
  setName: "Apollo 11",
  color: "Blue",
  perforation: "11",
  watermark: "None",
  theme: "Space",
  condition: "Mint",
  estimatedPrice: 6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Space", "USA"],
  description: "First Moon Landing commemorative",
},
{
  id: "15",
  catalogNumber: "RU-1981-01",
  country: "USSR",
  year: 1981,
  faceValue: "5k",
  topology: "Rectangular",
  fdc: false,
  setName: "Soviet Space Program",
  color: "Red",
  perforation: "12½",
  watermark: "None",
  theme: "Space",
  condition: "Used",
  estimatedPrice: 2.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Space", "Cold War"],
  description: "Soviet cosmonaut series",
},

// --- ASIA ---
{
  id: "16",
  catalogNumber: "CN-2008-OLY",
  country: "China",
  year: 2008,
  faceValue: "1.20¥",
  topology: "Rectangular",
  fdc: true,
  setName: "Beijing Olympics",
  color: "Red",
  perforation: "13",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Sports"],
  description: "Beijing Olympic Games stamp",
},
{
  id: "17",
  catalogNumber: "IN-1997-50Y",
  country: "India",
  year: 1997,
  faceValue: "5₹",
  topology: "Rectangular",
  fdc: false,
  setName: "Independence Anniversary",
  color: "Green",
  perforation: "14",
  watermark: "Ashoka Lion",
  theme: "History",
  condition: "Used",
  estimatedPrice: 1.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "History"],
  description: "50 years of Indian independence",
},

// --- AFRICA ---
{
  id: "18",
  catalogNumber: "EG-1985-01",
  country: "Egypt",
  year: 1985,
  faceValue: "10p",
  topology: "Rectangular",
  fdc: true,
  setName: "Ancient Egypt",
  color: "Gold",
  perforation: "12",
  watermark: "None",
  theme: "Archaeology",
  condition: "Mint",
  estimatedPrice: 3.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "History"],
  description: "Pyramids of Giza stamp",
},

// --- OCEANIA ---
{
  id: "19",
  catalogNumber: "NZ-2000-01",
  country: "New Zealand",
  year: 2000,
  faceValue: "$1.80",
  topology: "Rectangular",
  fdc: true,
  setName: "Millennium",
  color: "Blue",
  perforation: "14",
  watermark: "Silver Fern",
  theme: "Millennium",
  condition: "Mint",
  estimatedPrice: 4.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Millennium"],
  description: "Millennium commemorative stamp",
},
{
  id: "20",
  catalogNumber: "MX-1986-WC",
  country: "Mexico",
  year: 1986,
  faceValue: "50$",
  topology: "Rectangular",
  fdc: true,
  setName: "World Cup 1986",
  color: "Green",
  perforation: "13",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 3.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Sports", "America"],
  description: "Mexico World Cup 1986 commemorative",
},
{
  id: "21",
  catalogNumber: "AR-1978-WC",
  country: "Argentina",
  year: 1978,
  faceValue: "200P",
  topology: "Rectangular",
  fdc: false,
  setName: "World Cup 1978",
  color: "Blue",
  perforation: "13½",
  watermark: "None",
  theme: "Sports",
  condition: "Used",
  estimatedPrice: 2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Sports", "Football"],
  description: "Argentina World Cup stamp",
},
{
  id: "22",
  catalogNumber: "CL-1992-01",
  country: "Chile",
  year: 1992,
  faceValue: "120$",
  topology: "Rectangular",
  fdc: true,
  setName: "Discovery of America",
  color: "Brown",
  perforation: "14",
  watermark: "None",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 2.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["History", "America"],
  description: "500 years of discovery",
},
{
  id: "23",
  catalogNumber: "DE-1972-OLY",
  country: "Germany",
  year: 1972,
  faceValue: "30Pf",
  topology: "Rectangular",
  fdc: true,
  setName: "Munich Olympics",
  color: "Orange",
  perforation: "14",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Sports"],
  description: "Munich Olympic Games 1972",
},
{
  id: "24",
  catalogNumber: "SE-1995-EU",
  country: "Sweden",
  year: 1995,
  faceValue: "5Kr",
  topology: "Rectangular",
  fdc: false,
  setName: "Europa CEPT",
  color: "Blue",
  perforation: "13",
  watermark: "Crown",
  theme: "Europa",
  condition: "Used",
  estimatedPrice: 1.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Europa"],
  description: "Europa CEPT 1995 issue",
},
{
  id: "25",
  catalogNumber: "PL-1989-01",
  country: "Poland",
  year: 1989,
  faceValue: "20zł",
  topology: "Rectangular",
  fdc: true,
  setName: "Solidarity Movement",
  color: "Red",
  perforation: "12½",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 3.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Politics"],
  description: "Solidarity movement commemorative",
},
{
  id: "26",
  catalogNumber: "KR-1988-OLY",
  country: "South Korea",
  year: 1988,
  faceValue: "100W",
  topology: "Rectangular",
  fdc: true,
  setName: "Seoul Olympics",
  color: "Multicolor",
  perforation: "13",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Sports"],
  description: "Seoul Olympic Games",
},
{
  id: "27",
  catalogNumber: "TH-2006-60Y",
  country: "Thailand",
  year: 2006,
  faceValue: "5฿",
  topology: "Rectangular",
  fdc: false,
  setName: "King Rama IX",
  color: "Yellow",
  perforation: "14",
  watermark: "Garuda",
  theme: "Royalty",
  condition: "Used",
  estimatedPrice: 1.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Royalty"],
  description: "60th anniversary of reign",
},

{
  id: "30",
  catalogNumber: "PT-1987-02",
  country: "Portugal",
  year: 1987,
  faceValue: "30$00",
  topology: "Rectangular",
  fdc: false,
  setName: "Castelos de Portugal",
  color: "Brown",
  perforation: "14",
  watermark: "None",
  theme: "Architecture",
  condition: "Used",
  estimatedPrice: 1.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Architecture"],
  description: "Castle of Guimarães",
},
{
  id: "31",
  catalogNumber: "PT-1991-04",
  country: "Portugal",
  year: 1991,
  faceValue: "50$00",
  topology: "Rectangular",
  fdc: true,
  setName: "Discoveries",
  color: "Blue",
  perforation: "13½",
  watermark: "None",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 3.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Maritime"],
  description: "Age of Discoveries commemorative",
},
{
  id: "32",
  catalogNumber: "ES-1999-07",
  country: "Spain",
  year: 1999,
  faceValue: "35P",
  topology: "Rectangular",
  fdc: false,
  setName: "Fauna Ibérica",
  color: "Green",
  perforation: "14",
  watermark: "None",
  theme: "Animals",
  condition: "Used",
  estimatedPrice: 2.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Animals"],
  description: "Iberian lynx stamp",
},
{
  id: "33",
  catalogNumber: "FR-1984-ART",
  country: "France",
  year: 1984,
  faceValue: "2.20F",
  topology: "Rectangular",
  fdc: true,
  setName: "Impressionism",
  color: "Multicolor",
  perforation: "13",
  watermark: "None",
  theme: "Art",
  condition: "Mint",
  estimatedPrice: 4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Art"],
  description: "Claude Monet painting",
},
{
  id: "34",
  catalogNumber: "IT-1990-06",
  country: "Italy",
  year: 1990,
  faceValue: "750L",
  topology: "Rectangular",
  fdc: false,
  setName: "Roman Heritage",
  color: "Red",
  perforation: "14",
  watermark: "None",
  theme: "Archaeology",
  condition: "Used",
  estimatedPrice: 1.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "History"],
  description: "Roman Colosseum",
},
{
  id: "35",
  catalogNumber: "DE-2005-TECH",
  country: "Germany",
  year: 2005,
  faceValue: "55c",
  topology: "Rectangular",
  fdc: true,
  setName: "German Innovation",
  color: "Gray",
  perforation: "13¾",
  watermark: "None",
  theme: "Technology",
  condition: "Mint",
  estimatedPrice: 3.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Technology"],
  description: "Engineering achievements",
},
{
  id: "36",
  catalogNumber: "UK-1981-ROY",
  country: "United Kingdom",
  year: 1981,
  faceValue: "12p",
  topology: "Rectangular",
  fdc: false,
  setName: "Royal Wedding",
  color: "Purple",
  perforation: "15x14",
  watermark: "Crown",
  theme: "Royalty",
  condition: "Used",
  estimatedPrice: 2.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Royalty"],
  description: "Prince Charles & Diana wedding",
},
{
  id: "37",
  catalogNumber: "US-1995-CIV",
  country: "USA",
  year: 1995,
  faceValue: "$0.32",
  topology: "Rectangular",
  fdc: true,
  setName: "Civil War",
  color: "Sepia",
  perforation: "11",
  watermark: "None",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 3.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["America", "History"],
  description: "Civil War battles",
},
{
  id: "38",
  catalogNumber: "US-2001-09",
  country: "USA",
  year: 2001,
  faceValue: "$0.34",
  topology: "Rectangular",
  fdc: true,
  setName: "Heroes",
  color: "Black",
  perforation: "11",
  watermark: "None",
  theme: "Memorial",
  condition: "Mint",
  estimatedPrice: 5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["America", "Memorial"],
  description: "September 11 memorial",
},
{
  id: "39",
  catalogNumber: "BR-1994-FAU",
  country: "Brazil",
  year: 1994,
  faceValue: "500Cr",
  topology: "Rectangular",
  fdc: false,
  setName: "Amazon Fauna",
  color: "Green",
  perforation: "13",
  watermark: "None",
  theme: "Animals",
  condition: "Used",
  estimatedPrice: 1.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Nature"],
  description: "Amazon rainforest animal",
},
{
  id: "40",
  catalogNumber: "JP-2002-WC",
  country: "Japan",
  year: 2002,
  faceValue: "80¥",
  topology: "Rectangular",
  fdc: true,
  setName: "World Cup 2002",
  color: "Blue",
  perforation: "13",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 3.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Football"],
  description: "FIFA World Cup Korea/Japan",
},
{
  id: "41",
  catalogNumber: "CN-1997-HK",
  country: "China",
  year: 1997,
  faceValue: "50f",
  topology: "Rectangular",
  fdc: true,
  setName: "Hong Kong Return",
  color: "Red",
  perforation: "13½",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 4.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "History"],
  description: "Hong Kong handover",
},
{
  id: "42",
  catalogNumber: "IN-2003-TRN",
  country: "India",
  year: 2003,
  faceValue: "5₹",
  topology: "Rectangular",
  fdc: false,
  setName: "Indian Railways",
  color: "Brown",
  perforation: "14",
  watermark: "Ashoka Lion",
  theme: "Transport",
  condition: "Used",
  estimatedPrice: 1.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Trains"],
  description: "Historic steam locomotive",
},
{
  id: "43",
  catalogNumber: "EG-1979-01",
  country: "Egypt",
  year: 1979,
  faceValue: "20p",
  topology: "Rectangular",
  fdc: true,
  setName: "Peace Treaty",
  color: "Blue",
  perforation: "12½",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 3.3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "History"],
  description: "Egypt-Israel peace treaty",
},
{
  id: "44",
  catalogNumber: "ZA-2010-WC",
  country: "South Africa",
  year: 2010,
  faceValue: "2.50R",
  topology: "Rectangular",
  fdc: true,
  setName: "World Cup 2010",
  color: "Multicolor",
  perforation: "14",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 4.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "Football"],
  description: "2010 FIFA World Cup",
},
{
  id: "45",
  catalogNumber: "AU-1996-OLY",
  country: "Australia",
  year: 1996,
  faceValue: "45c",
  topology: "Rectangular",
  fdc: false,
  setName: "Olympic Games",
  color: "Blue",
  perforation: "14",
  watermark: "None",
  theme: "Sports",
  condition: "Used",
  estimatedPrice: 2.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Sports"],
  description: "Atlanta Olympics participation",
},
{
  id: "46",
  catalogNumber: "NZ-1984-NAT",
  country: "New Zealand",
  year: 1984,
  faceValue: "$1",
  topology: "Rectangular",
  fdc: true,
  setName: "National Parks",
  color: "Green",
  perforation: "13",
  watermark: "Fern",
  theme: "Nature",
  condition: "Mint",
  estimatedPrice: 3.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Nature"],
  description: "Fiordland National Park",
},
{
  id: "47",
  catalogNumber: "RU-1975-ART",
  country: "USSR",
  year: 1975,
  faceValue: "10k",
  topology: "Rectangular",
  fdc: false,
  setName: "Russian Art",
  color: "Brown",
  perforation: "12",
  watermark: "None",
  theme: "Art",
  condition: "Used",
  estimatedPrice: 1.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Art"],
  description: "Classical Russian painting",
},
{
  id: "48",
  catalogNumber: "GR-2004-OLY",
  country: "Greece",
  year: 2004,
  faceValue: "0.60€",
  topology: "Rectangular",
  fdc: true,
  setName: "Athens Olympics",
  color: "Blue",
  perforation: "14",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Sports"],
  description: "Athens Olympic Games",
},
{
  id: "49",
  catalogNumber: "NO-1994-01",
  country: "Norway",
  year: 1994,
  faceValue: "5Kr",
  topology: "Rectangular",
  fdc: false,
  setName: "Winter Olympics",
  color: "White",
  perforation: "13",
  watermark: "None",
  theme: "Sports",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Winter Sports"],
  description: "Lillehammer Olympics",
},
{
  id: "50",
  catalogNumber: "PT-1974-01",
  country: "Portugal",
  year: 1974,
  faceValue: "10$00",
  topology: "Rectangular",
  fdc: true,
  setName: "25 de Abril",
  color: "Red",
  perforation: "14x14",
  watermark: "None",
  theme: "Revolution",
  condition: "Mint",
  estimatedPrice: 12,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Politics"],
  description: "Carnation Revolution commemorative issue",
},
{
  id: "51",
  catalogNumber: "FR-1989-03",
  country: "France",
  year: 1989,
  faceValue: "2.20F",
  topology: "Rectangular",
  fdc: true,
  setName: "Bicentennial of the Revolution",
  color: "Blue",
  perforation: "13x13",
  watermark: "Marianne",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Revolution"],
  description: "200 years of the French Revolution",
},
{
  id: "52",
  catalogNumber: "DE-1995-11",
  country: "Germany",
  year: 1995,
  faceValue: "100pf",
  topology: "Rectangular",
  fdc: false,
  setName: "Industrial Heritage",
  color: "Gray",
  perforation: "14x13½",
  watermark: "None",
  theme: "Industry",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Industry"],
  description: "German industrial landmark series",
},
{
  id: "53",
  catalogNumber: "UK-1966-04",
  country: "United Kingdom",
  year: 1966,
  faceValue: "4d",
  topology: "Rectangular",
  fdc: false,
  setName: "World Cup",
  color: "Red",
  perforation: "15x14",
  watermark: "Crown",
  theme: "Sports",
  condition: "Used",
  estimatedPrice: 3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Football"],
  description: "England World Cup victory issue",
},
{
  id: "54",
  catalogNumber: "US-1969-01",
  country: "USA",
  year: 1969,
  faceValue: "$0.10",
  topology: "Rectangular",
  fdc: true,
  setName: "First Man on the Moon",
  color: "Blue",
  perforation: "11x11",
  watermark: "Eagle",
  theme: "Space",
  condition: "Mint",
  estimatedPrice: 15,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["America", "Space"],
  description: "Apollo 11 commemorative stamp",
},
{
  id: "55",
  catalogNumber: "JP-1970-05",
  country: "Japan",
  year: 1970,
  faceValue: "50¥",
  topology: "Rectangular",
  fdc: true,
  setName: "Expo ’70 Osaka",
  color: "Multicolor",
  perforation: "13x13",
  watermark: "None",
  theme: "Expo",
  condition: "Mint",
  estimatedPrice: 6.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Expo"],
  description: "World Expo Osaka 1970",
},
{
  id: "56",
  catalogNumber: "IT-1999-02",
  country: "Italy",
  year: 1999,
  faceValue: "800L",
  topology: "Rectangular",
  fdc: false,
  setName: "Italian Cinema",
  color: "Sepia",
  perforation: "14x14",
  watermark: "Star",
  theme: "Cinema",
  condition: "Used",
  estimatedPrice: 2.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Cinema"],
  description: "Classic Italian film tribute",
},
{
  id: "57",
  catalogNumber: "BR-1988-01",
  country: "Brazil",
  year: 1988,
  faceValue: "50Cz$",
  topology: "Rectangular",
  fdc: true,
  setName: "Federal Constitution",
  color: "Green",
  perforation: "13½x13",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Law"],
  description: "Brazilian Constitution of 1988",
},
{
  id: "58",
  catalogNumber: "CA-1992-07",
  country: "Canada",
  year: 1992,
  faceValue: "$0.42",
  topology: "Rectangular",
  fdc: true,
  setName: "Indigenous Art",
  color: "Multicolor",
  perforation: "13x13",
  watermark: "Maple Leaf",
  theme: "Culture",
  condition: "Mint",
  estimatedPrice: 5.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["America", "Indigenous"],
  description: "Native Canadian art representation",
},
{
  id: "59",
  catalogNumber: "AU-1981-03",
  country: "Australia",
  year: 1981,
  faceValue: "24c",
  topology: "Rectangular",
  fdc: false,
  setName: "Endangered Species",
  color: "Brown",
  perforation: "14x14",
  watermark: "Kangaroo",
  theme: "Nature",
  condition: "Used",
  estimatedPrice: 2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Animals"],
  description: "Threatened wildlife issue",
},
{
  id: "60",
  catalogNumber: "NL-2002-01",
  country: "Netherlands",
  year: 2002,
  faceValue: "0.39€",
  topology: "Rectangular",
  fdc: true,
  setName: "Euro Introduction",
  color: "Blue",
  perforation: "14x13",
  watermark: "None",
  theme: "Currency",
  condition: "Mint",
  estimatedPrice: 3.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Euro"],
  description: "Introduction of the Euro currency",
},
{
  id: "61",
  catalogNumber: "SE-1975-06",
  country: "Sweden",
  year: 1975,
  faceValue: "1.40kr",
  topology: "Rectangular",
  fdc: false,
  setName: "Nordic Wildlife",
  color: "Green",
  perforation: "13x13",
  watermark: "Crown",
  theme: "Animals",
  condition: "Used",
  estimatedPrice: 2.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Nature"],
  description: "Nordic forest animal series",
},
{
  id: "62",
  catalogNumber: "NO-1987-02",
  country: "Norway",
  year: 1987,
  faceValue: "3kr",
  topology: "Rectangular",
  fdc: true,
  setName: "Viking Ships",
  color: "Blue",
  perforation: "13½x13",
  watermark: "None",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 4.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Vikings"],
  description: "Historic Viking longship",
},
{
  id: "63",
  catalogNumber: "FI-1998-04",
  country: "Finland",
  year: 1998,
  faceValue: "3.40mk",
  topology: "Rectangular",
  fdc: false,
  setName: "Modern Design",
  color: "White",
  perforation: "14x14",
  watermark: "None",
  theme: "Design",
  condition: "Used",
  estimatedPrice: 1.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Design"],
  description: "Minimalist Finnish stamp design",
},
{
  id: "64",
  catalogNumber: "GR-2004-01",
  country: "Greece",
  year: 2004,
  faceValue: "0.60€",
  topology: "Rectangular",
  fdc: true,
  setName: "Athens Olympics",
  color: "Blue",
  perforation: "13x13",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 6.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Olympics"],
  description: "Athens Olympic Games 2004",
},
{
  id: "65",
  catalogNumber: "IE-1990-03",
  country: "Ireland",
  year: 1990,
  faceValue: "20p",
  topology: "Rectangular",
  fdc: false,
  setName: "Celtic Art",
  color: "Green",
  perforation: "14x14",
  watermark: "Harp",
  theme: "Art",
  condition: "Used",
  estimatedPrice: 2.3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Celtic"],
  description: "Traditional Celtic knotwork",
},
{
  id: "66",
  catalogNumber: "BE-1980-05",
  country: "Belgium",
  year: 1980,
  faceValue: "12F",
  topology: "Rectangular",
  fdc: true,
  setName: "European Architecture",
  color: "Brown",
  perforation: "13½x13",
  watermark: "None",
  theme: "Architecture",
  condition: "Mint",
  estimatedPrice: 3.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Buildings"],
  description: "Historic Belgian buildings",
},
{
  id: "67",
  catalogNumber: "AT-1976-02",
  country: "Austria",
  year: 1976,
  faceValue: "3S",
  topology: "Rectangular",
  fdc: false,
  setName: "Composers",
  color: "Purple",
  perforation: "14x13",
  watermark: "None",
  theme: "Music",
  condition: "Used",
  estimatedPrice: 2.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Music"],
  description: "Famous Austrian composer",
},
{
  id: "68",
  catalogNumber: "CZ-1993-01",
  country: "Czech Republic",
  year: 1993,
  faceValue: "8Kč",
  topology: "Rectangular",
  fdc: true,
  setName: "New Republic",
  color: "Blue",
  perforation: "13x13",
  watermark: "Lion",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 4.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Independence"],
  description: "Formation of the Czech Republic",
},
{
  id: "69",
  catalogNumber: "PL-1983-04",
  country: "Poland",
  year: 1983,
  faceValue: "10zł",
  topology: "Rectangular",
  fdc: false,
  setName: "Solidarity Movement",
  color: "Red",
  perforation: "14x14",
  watermark: "None",
  theme: "Politics",
  condition: "Used",
  estimatedPrice: 3.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Labor"],
  description: "Solidarity trade union era",
},
{
  id: "70",
  catalogNumber: "HU-1971-06",
  country: "Hungary",
  year: 1971,
  faceValue: "2Ft",
  topology: "Rectangular",
  fdc: true,
  setName: "Space Research",
  color: "Blue",
  perforation: "12½x12",
  watermark: "None",
  theme: "Space",
  condition: "Mint",
  estimatedPrice: 4.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Science"],
  description: "Hungarian space program",
},
{
  id: "71",
  catalogNumber: "MX-1995-08",
  country: "Mexico",
  year: 1995,
  faceValue: "$2.50",
  topology: "Rectangular",
  fdc: false,
  setName: "Ancient Civilizations",
  color: "Brown",
  perforation: "13x13",
  watermark: "None",
  theme: "History",
  condition: "Used",
  estimatedPrice: 2.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["America", "Aztec"],
  description: "Aztec pyramid illustration",
},
{
  id: "72",
  catalogNumber: "AR-1978-02",
  country: "Argentina",
  year: 1978,
  faceValue: "$50",
  topology: "Rectangular",
  fdc: true,
  setName: "World Cup",
  color: "Blue",
  perforation: "14x14",
  watermark: "Sun",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 5.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Football"],
  description: "Argentina World Cup champions",
},
{
  id: "73",
  catalogNumber: "ZA-1994-01",
  country: "South Africa",
  year: 1994,
  faceValue: "1R",
  topology: "Rectangular",
  fdc: true,
  setName: "First Democratic Elections",
  color: "Multicolor",
  perforation: "13x13",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 6.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "Democracy"],
  description: "End of apartheid elections",
},
{
  id: "74",
  catalogNumber: "EG-1982-04",
  country: "Egypt",
  year: 1982,
  faceValue: "20m",
  topology: "Rectangular",
  fdc: false,
  setName: "Ancient Egypt",
  color: "Gold",
  perforation: "13½x13",
  watermark: "None",
  theme: "Archaeology",
  condition: "Used",
  estimatedPrice: 2.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "History"],
  description: "Pharaoh relief illustration",
},
{
  id: "75",
  catalogNumber: "CN-2008-02",
  country: "China",
  year: 2008,
  faceValue: "1.20¥",
  topology: "Rectangular",
  fdc: true,
  setName: "Beijing Olympics",
  color: "Red",
  perforation: "13x13",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 8.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Olympics"],
  description: "Beijing 2008 Olympic Games",
},
{
  id: "76",
  catalogNumber: "IN-1985-07",
  country: "India",
  year: 1985,
  faceValue: "50p",
  topology: "Rectangular",
  fdc: false,
  setName: "Indian Railways",
  color: "Green",
  perforation: "14x14",
  watermark: "Ashoka Lion",
  theme: "Transport",
  condition: "Used",
  estimatedPrice: 1.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Railways"],
  description: "Indian railway locomotive",
},
{
  id: "77",
  catalogNumber: "RU-1967-03",
  country: "USSR",
  year: 1967,
  faceValue: "10k",
  topology: "Rectangular",
  fdc: true,
  setName: "October Revolution",
  color: "Red",
  perforation: "12x12",
  watermark: "Hammer & Sickle",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Communism"],
  description: "50th anniversary of the revolution",
},
{
  id: "78",
  catalogNumber: "DK-1996-05",
  country: "Denmark",
  year: 1996,
  faceValue: "3.75kr",
  topology: "Rectangular",
  fdc: false,
  setName: "Modern Architecture",
  color: "Gray",
  perforation: "13x13",
  watermark: "Crown",
  theme: "Architecture",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Design"],
  description: "Contemporary Danish building",
},
{
  id: "79",
  catalogNumber: "IS-1980-01",
  country: "Iceland",
  year: 1980,
  faceValue: "15kr",
  topology: "Rectangular",
  fdc: true,
  setName: "Volcanoes",
  color: "Black",
  perforation: "14x14",
  watermark: "None",
  theme: "Nature",
  condition: "Mint",
  estimatedPrice: 4.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Geology"],
  description: "Active volcano depiction",
},
{
  id: "80",
  catalogNumber: "NZ-1991-06",
  country: "New Zealand",
  year: 1991,
  faceValue: "45c",
  topology: "Rectangular",
  fdc: false,
  setName: "Native Birds",
  color: "Green",
  perforation: "13x13",
  watermark: "Kiwi",
  theme: "Animals",
  condition: "Used",
  estimatedPrice: 2.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Birds"],
  description: "Native New Zealand bird species",
},
{
  id: "81",
  catalogNumber: "PT-2007-03",
  country: "Portugal",
  year: 2007,
  faceValue: "0.30€",
  topology: "Rectangular",
  fdc: true,
  setName: "Portuguese Discoveries",
  color: "Blue",
  perforation: "14x13",
  watermark: "Armillary Sphere",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 3.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Exploration"],
  description: "Age of Discoveries series",
},
{
  id: "82",
  catalogNumber: "ES-1986-04",
  country: "Spain",
  year: 1986,
  faceValue: "19P",
  topology: "Rectangular",
  fdc: false,
  setName: "World Heritage Sites",
  color: "Brown",
  perforation: "13x13",
  watermark: "None",
  theme: "Architecture",
  condition: "Used",
  estimatedPrice: 2.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "UNESCO"],
  description: "Historic Spanish landmark",
},
{
  id: "83",
  catalogNumber: "RO-1970-08",
  country: "Romania",
  year: 1970,
  faceValue: "1.60L",
  topology: "Rectangular",
  fdc: true,
  setName: "Carpathian Wildlife",
  color: "Green",
  perforation: "12½x12",
  watermark: "None",
  theme: "Animals",
  condition: "Mint",
  estimatedPrice: 3.3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Nature"],
  description: "Bear from the Carpathian Mountains",
},
{
  id: "84",
  catalogNumber: "TR-1981-02",
  country: "Turkey",
  year: 1981,
  faceValue: "5TL",
  topology: "Rectangular",
  fdc: false,
  setName: "Atatürk",
  color: "Black",
  perforation: "14x14",
  watermark: "None",
  theme: "Leaders",
  condition: "Used",
  estimatedPrice: 2.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Politics"],
  description: "Mustafa Kemal Atatürk portrait",
},
{
  id: "85",
  catalogNumber: "IL-1998-01",
  country: "Israel",
  year: 1998,
  faceValue: "1.30₪",
  topology: "Rectangular",
  fdc: true,
  setName: "Jerusalem 3000",
  color: "Gold",
  perforation: "13x13",
  watermark: "Menorah",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 5.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Middle East", "Religion"],
  description: "3000 years of Jerusalem",
},
{
  id: "86",
  catalogNumber: "KR-2000-06",
  country: "South Korea",
  year: 2000,
  faceValue: "250₩",
  topology: "Rectangular",
  fdc: false,
  setName: "Information Age",
  color: "Blue",
  perforation: "13½x13",
  watermark: "None",
  theme: "Technology",
  condition: "Used",
  estimatedPrice: 2.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Tech"],
  description: "Digital era celebration",
},
{
  id: "87",
  catalogNumber: "TH-1996-04",
  country: "Thailand",
  year: 1996,
  faceValue: "5B",
  topology: "Rectangular",
  fdc: true,
  setName: "Royal Jubilee",
  color: "Purple",
  perforation: "14x14",
  watermark: "Garuda",
  theme: "Royalty",
  condition: "Mint",
  estimatedPrice: 4.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Monarchy"],
  description: "King Bhumibol jubilee issue",
},
{
  id: "88",
  catalogNumber: "CL-1973-01",
  country: "Chile",
  year: 1973,
  faceValue: "2Eº",
  topology: "Rectangular",
  fdc: false,
  setName: "Chilean Landscapes",
  color: "Green",
  perforation: "13x13",
  watermark: "None",
  theme: "Nature",
  condition: "Used",
  estimatedPrice: 1.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Landscapes"],
  description: "Andes mountain scenery",
},
{
  id: "89",
  catalogNumber: "CO-1984-05",
  country: "Colombia",
  year: 1984,
  faceValue: "$10",
  topology: "Rectangular",
  fdc: true,
  setName: "Coffee Culture",
  color: "Brown",
  perforation: "14x14",
  watermark: "None",
  theme: "Agriculture",
  condition: "Mint",
  estimatedPrice: 3.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Coffee"],
  description: "Colombian coffee production",
},
{
  id: "90",
  catalogNumber: "PE-1991-02",
  country: "Peru",
  year: 1991,
  faceValue: "500I",
  topology: "Rectangular",
  fdc: false,
  setName: "Inca Heritage",
  color: "Brown",
  perforation: "13½x13",
  watermark: "None",
  theme: "Archaeology",
  condition: "Used",
  estimatedPrice: 2.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Inca"],
  description: "Machu Picchu illustration",
},
{
  id: "91",
  catalogNumber: "VE-1980-03",
  country: "Venezuela",
  year: 1980,
  faceValue: "1Bs",
  topology: "Rectangular",
  fdc: true,
  setName: "Oil Industry",
  color: "Black",
  perforation: "14x14",
  watermark: "None",
  theme: "Industry",
  condition: "Mint",
  estimatedPrice: 3.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["South America", "Energy"],
  description: "Petroleum extraction facilities",
},
{
  id: "92",
  catalogNumber: "MY-1998-01",
  country: "Malaysia",
  year: 1998,
  faceValue: "30s",
  topology: "Rectangular",
  fdc: false,
  setName: "Rainforest",
  color: "Green",
  perforation: "13x13",
  watermark: "None",
  theme: "Nature",
  condition: "Used",
  estimatedPrice: 2.3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Rainforest"],
  description: "Tropical rainforest species",
},
{
  id: "93",
  catalogNumber: "PH-1996-02",
  country: "Philippines",
  year: 1996,
  faceValue: "5₱",
  topology: "Rectangular",
  fdc: true,
  setName: "National Heroes",
  color: "Blue",
  perforation: "14x14",
  watermark: "None",
  theme: "Leaders",
  condition: "Mint",
  estimatedPrice: 3.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "History"],
  description: "José Rizal commemorative stamp",
},
{
  id: "94",
  catalogNumber: "ID-1987-06",
  country: "Indonesia",
  year: 1987,
  faceValue: "50Rp",
  topology: "Rectangular",
  fdc: false,
  setName: "Traditional Dance",
  color: "Multicolor",
  perforation: "13x13",
  watermark: "None",
  theme: "Culture",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Dance"],
  description: "Balinese dance performance",
},
{
  id: "95",
  catalogNumber: "VN-2000-04",
  country: "Vietnam",
  year: 2000,
  faceValue: "400đ",
  topology: "Rectangular",
  fdc: true,
  setName: "Millennium",
  color: "Red",
  perforation: "13½x13",
  watermark: "None",
  theme: "Millennium",
  condition: "Mint",
  estimatedPrice: 3.4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "2000s"],
  description: "Turn of the millennium issue",
},
{
  id: "96",
  catalogNumber: "IR-1979-01",
  country: "Iran",
  year: 1979,
  faceValue: "20R",
  topology: "Rectangular",
  fdc: false,
  setName: "Islamic Revolution",
  color: "Black",
  perforation: "12½x12",
  watermark: "None",
  theme: "Politics",
  condition: "Used",
  estimatedPrice: 2.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Middle East", "Revolution"],
  description: "Post-revolution Iranian issue",
},
{
  id: "97",
  catalogNumber: "SA-1986-03",
  country: "Saudi Arabia",
  year: 1986,
  faceValue: "50h",
  topology: "Rectangular",
  fdc: true,
  setName: "Holy Mosques",
  color: "Green",
  perforation: "14x14",
  watermark: "Palm Tree",
  theme: "Religion",
  condition: "Mint",
  estimatedPrice: 4.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Middle East", "Islam"],
  description: "Grand Mosque of Mecca",
},
{
  id: "98",
  catalogNumber: "KE-1990-02",
  country: "Kenya",
  year: 1990,
  faceValue: "5Sh",
  topology: "Rectangular",
  fdc: false,
  setName: "African Wildlife",
  color: "Brown",
  perforation: "13x13",
  watermark: "None",
  theme: "Animals",
  condition: "Used",
  estimatedPrice: 2.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "Safari"],
  description: "African elephant",
},
{
  id: "99",
  catalogNumber: "TZ-1985-04",
  country: "Tanzania",
  year: 1985,
  faceValue: "10Sh",
  topology: "Rectangular",
  fdc: true,
  setName: "Mount Kilimanjaro",
  color: "Blue",
  perforation: "14x14",
  watermark: "None",
  theme: "Geography",
  condition: "Mint",
  estimatedPrice: 3.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "Mountains"],
  description: "Highest peak in Africa",
},
{
  id: "100",
  catalogNumber: "MA-2001-01",
  country: "Morocco",
  year: 2001,
  faceValue: "3DH",
  topology: "Rectangular",
  fdc: true,
  setName: "Traditional Crafts",
  color: "Multicolor",
  perforation: "13x13",
  watermark: "None",
  theme: "Culture",
  condition: "Mint",
  estimatedPrice: 3.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "Crafts"],
  description: "Moroccan artisan traditions",
},


];
