import { Stamp } from "@/components/StampCard";

export const DEMO_STAMPS: Stamp[] = [
  {
    id: "1",
    catalogNumber: "PT-1995-01",
    country: "Portugal",
    year: 1995,
    faceValue: "1€",
    topology: "Rectangular",
    fdc: true,
    setName: "Europa 1995",
    color: "Blue",
    perforation: "14x14",
    watermark: "None",
    theme: "Historical Figures",
    condition: "Mint",
    estimatedPrice: 5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "History"],
    description: "Commemorative stamp featuring King João II",
  },
  {
    id: "2",
    catalogNumber: "FR-2000-12",
    country: "France",
    year: 2000,
    faceValue: "2€",
    topology: "Square",
    fdc: false,
    setName: "Millennium",
    color: "Red",
    perforation: "13x13",
    watermark: "Small fleur-de-lis",
    theme: "Millennium Celebration",
    condition: "Used",
    estimatedPrice: 3,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Millennium"],
    description: "Square stamp issued for the millennium celebration in France",
  },
  {
    id: "3",
    catalogNumber: "DE-1980-05",
    country: "Germany",
    year: 1980,
    faceValue: "0.50€",
    topology: "Rectangular",
    fdc: true,
    setName: "Animals Series",
    color: "Brown",
    perforation: "14x14",
    watermark: "None",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 2.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Animals"],
    description: "Rectangular stamp featuring a German eagle",
  },
  {
    id: "4",
    catalogNumber: "US-1975-03",
    country: "USA",
    year: 1975,
    faceValue: "$0.10",
    topology: "Circular",
    fdc: false,
    setName: "Historic Figures",
    color: "Red",
    perforation: "12x12",
    watermark: "Liberty Bell",
    theme: "Presidents",
    condition: "Used",
    estimatedPrice: 1,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["America", "History"],
    description: "Circular stamp featuring US president",
  },
  {
    id: "5",
    catalogNumber: "UK-2010-01",
    country: "United Kingdom",
    year: 2010,
    faceValue: "£1",
    topology: "Rectangular",
    fdc: true,
    setName: "Royalty",
    color: "Blue",
    perforation: "14x14",
    watermark: "Crown",
    theme: "Queen Elizabeth II",
    condition: "Mint",
    estimatedPrice: 6,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Royalty"],
    description: "Commemorative stamp featuring Queen Elizabeth II",
  },
  // Add more for variety
  {
    id: "6",
    catalogNumber: "JP-1990-04",
    country: "Japan",
    year: 1990,
    faceValue: "100¥",
    topology: "Rectangular",
    fdc: true,
    setName: "Cherry Blossom",
    color: "Pink",
    perforation: "13x13",
    watermark: "Cherry",
    theme: "Nature",
    condition: "Mint",
    estimatedPrice: 4,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Asia", "Nature"],
    description: "Cherry Blossom stamp from Japan",
  },
  {
    id: "7",
    catalogNumber: "IT-1985-09",
    country: "Italy",
    year: 1985,
    faceValue: "500L",
    topology: "Rectangular",
    fdc: false,
    setName: "Art Series",
    color: "Multicolor",
    perforation: "14x14",
    watermark: "None",
    theme: "Renaissance",
    condition: "Used",
    estimatedPrice: 3.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Europe", "Art"],
    description: "Renaissance painting featured on stamp",
  },
  {
    id: "8",
    catalogNumber: "CA-2005-02",
    country: "Canada",
    year: 2005,
    faceValue: "1.50$",
    topology: "Square",
    fdc: true,
    setName: "Wildlife",
    color: "Green",
    perforation: "13x13",
    watermark: "Maple Leaf",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 4.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["America", "Nature"],
    description: "Canadian wildlife stamp",
  },
  {
    id: "9",
    catalogNumber: "AU-2015-01",
    country: "Australia",
    year: 2015,
    faceValue: "2$",
    topology: "Rectangular",
    fdc: true,
    setName: "Nature Series",
    color: "Blue",
    perforation: "14x14",
    watermark: "Kangaroo",
    theme: "Animals",
    condition: "Mint",
    estimatedPrice: 5.5,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["Oceania", "Nature"],
    description: "Australian stamp featuring kangaroo",
  },
  {
    id: "10",
    catalogNumber: "BR-2001-07",
    country: "Brazil",
    year: 2001,
    faceValue: "R$1.20",
    topology: "Rectangular",
    fdc: false,
    setName: "Carnival",
    color: "Red",
    perforation: "13x13",
    watermark: "None",
    theme: "Culture",
    condition: "Used",
    estimatedPrice: 2.8,
    lastPriceUpdate: "2026-02-06T00:00:00Z",
    image: "/placeholder-stamp.png",
    tags: ["South America", "Culture"],
    description: "Brazil Carnival stamp",
  },
// --- EUROPE ---
{
  id: "11",
  catalogNumber: "ES-1982-OLY",
  country: "Spain",
  year: 1982,
  faceValue: "25P",
  topology: "Rectangular",
  fdc: true,
  setName: "Barcelona Olympics",
  color: "Multicolor",
  perforation: "13¾",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Sports"],
  description: "Issued for the 1982 Olympic Games",
},
{
  id: "12",
  catalogNumber: "NL-1998-01",
  country: "Netherlands",
  year: 1998,
  faceValue: "80c",
  topology: "Rectangular",
  fdc: false,
  setName: "Modern Art",
  color: "Yellow",
  perforation: "14",
  watermark: "None",
  theme: "Art",
  condition: "Used",
  estimatedPrice: 2.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Art"],
  description: "Modern Dutch art stamp",
},
{
  id: "13",
  catalogNumber: "CH-1970-05",
  country: "Switzerland",
  year: 1970,
  faceValue: "50Rp",
  topology: "Rectangular",
  fdc: true,
  setName: "Alpine Flowers",
  color: "Purple",
  perforation: "11¾",
  watermark: "Cross",
  theme: "Nature",
  condition: "Mint",
  estimatedPrice: 3,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Nature"],
  description: "Alpine flower series",
},

// --- CLASSIC THEMES ---
{
  id: "14",
  catalogNumber: "US-1969-AP11",
  country: "USA",
  year: 1969,
  faceValue: "$0.10",
  topology: "Rectangular",
  fdc: true,
  setName: "Apollo 11",
  color: "Blue",
  perforation: "11",
  watermark: "None",
  theme: "Space",
  condition: "Mint",
  estimatedPrice: 6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Space", "USA"],
  description: "First Moon Landing commemorative",
},
{
  id: "15",
  catalogNumber: "RU-1981-01",
  country: "USSR",
  year: 1981,
  faceValue: "5k",
  topology: "Rectangular",
  fdc: false,
  setName: "Soviet Space Program",
  color: "Red",
  perforation: "12½",
  watermark: "None",
  theme: "Space",
  condition: "Used",
  estimatedPrice: 2.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Space", "Cold War"],
  description: "Soviet cosmonaut series",
},

// --- ASIA ---
{
  id: "16",
  catalogNumber: "CN-2008-OLY",
  country: "China",
  year: 2008,
  faceValue: "1.20¥",
  topology: "Rectangular",
  fdc: true,
  setName: "Beijing Olympics",
  color: "Red",
  perforation: "13",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Sports"],
  description: "Beijing Olympic Games stamp",
},
{
  id: "17",
  catalogNumber: "IN-1997-50Y",
  country: "India",
  year: 1997,
  faceValue: "5₹",
  topology: "Rectangular",
  fdc: false,
  setName: "Independence Anniversary",
  color: "Green",
  perforation: "14",
  watermark: "Ashoka Lion",
  theme: "History",
  condition: "Used",
  estimatedPrice: 1.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "History"],
  description: "50 years of Indian independence",
},

// --- AFRICA ---
{
  id: "18",
  catalogNumber: "EG-1985-01",
  country: "Egypt",
  year: 1985,
  faceValue: "10p",
  topology: "Rectangular",
  fdc: true,
  setName: "Ancient Egypt",
  color: "Gold",
  perforation: "12",
  watermark: "None",
  theme: "Archaeology",
  condition: "Mint",
  estimatedPrice: 3.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Africa", "History"],
  description: "Pyramids of Giza stamp",
},

// --- OCEANIA ---
{
  id: "19",
  catalogNumber: "NZ-2000-01",
  country: "New Zealand",
  year: 2000,
  faceValue: "$1.80",
  topology: "Rectangular",
  fdc: true,
  setName: "Millennium",
  color: "Blue",
  perforation: "14",
  watermark: "Silver Fern",
  theme: "Millennium",
  condition: "Mint",
  estimatedPrice: 4.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Oceania", "Millennium"],
  description: "Millennium commemorative stamp",
},
{
  id: "20",
  catalogNumber: "MX-1986-WC",
  country: "Mexico",
  year: 1986,
  faceValue: "50$",
  topology: "Rectangular",
  fdc: true,
  setName: "World Cup 1986",
  color: "Green",
  perforation: "13",
  watermark: "None",
  theme: "Sports",
  condition: "Mint",
  estimatedPrice: 3.5,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Sports", "America"],
  description: "Mexico World Cup 1986 commemorative",
},
{
  id: "21",
  catalogNumber: "AR-1978-WC",
  country: "Argentina",
  year: 1978,
  faceValue: "200P",
  topology: "Rectangular",
  fdc: false,
  setName: "World Cup 1978",
  color: "Blue",
  perforation: "13½",
  watermark: "None",
  theme: "Sports",
  condition: "Used",
  estimatedPrice: 2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Sports", "Football"],
  description: "Argentina World Cup stamp",
},
{
  id: "22",
  catalogNumber: "CL-1992-01",
  country: "Chile",
  year: 1992,
  faceValue: "120$",
  topology: "Rectangular",
  fdc: true,
  setName: "Discovery of America",
  color: "Brown",
  perforation: "14",
  watermark: "None",
  theme: "History",
  condition: "Mint",
  estimatedPrice: 2.7,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["History", "America"],
  description: "500 years of discovery",
},
{
  id: "23",
  catalogNumber: "DE-1972-OLY",
  country: "Germany",
  year: 1972,
  faceValue: "30Pf",
  topology: "Rectangular",
  fdc: true,
  setName: "Munich Olympics",
  color: "Orange",
  perforation: "14",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4.8,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Sports"],
  description: "Munich Olympic Games 1972",
},
{
  id: "24",
  catalogNumber: "SE-1995-EU",
  country: "Sweden",
  year: 1995,
  faceValue: "5Kr",
  topology: "Rectangular",
  fdc: false,
  setName: "Europa CEPT",
  color: "Blue",
  perforation: "13",
  watermark: "Crown",
  theme: "Europa",
  condition: "Used",
  estimatedPrice: 1.9,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Europa"],
  description: "Europa CEPT 1995 issue",
},
{
  id: "25",
  catalogNumber: "PL-1989-01",
  country: "Poland",
  year: 1989,
  faceValue: "20zł",
  topology: "Rectangular",
  fdc: true,
  setName: "Solidarity Movement",
  color: "Red",
  perforation: "12½",
  watermark: "None",
  theme: "Politics",
  condition: "Mint",
  estimatedPrice: 3.2,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Europe", "Politics"],
  description: "Solidarity movement commemorative",
},
{
  id: "26",
  catalogNumber: "KR-1988-OLY",
  country: "South Korea",
  year: 1988,
  faceValue: "100W",
  topology: "Rectangular",
  fdc: true,
  setName: "Seoul Olympics",
  color: "Multicolor",
  perforation: "13",
  watermark: "None",
  theme: "Olympics",
  condition: "Mint",
  estimatedPrice: 4.1,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Sports"],
  description: "Seoul Olympic Games",
},
{
  id: "27",
  catalogNumber: "TH-2006-60Y",
  country: "Thailand",
  year: 2006,
  faceValue: "5฿",
  topology: "Rectangular",
  fdc: false,
  setName: "King Rama IX",
  color: "Yellow",
  perforation: "14",
  watermark: "Garuda",
  theme: "Royalty",
  condition: "Used",
  estimatedPrice: 1.6,
  lastPriceUpdate: "2026-02-06T00:00:00Z",
  image: "/placeholder-stamp.png",
  tags: ["Asia", "Royalty"],
  description: "60th anniversary of reign",
},

];
